### ISSUE TITLE
I2C JavaScript Driver

### ISSUE THREAD

**Issue by nfcopier** [USU-Robosub/Poseidon#137]
## Summary

The I2C driver needs to be converted to JavaScript. It was suggested that the I2C has some low-level requirements that prevent it from being converted. If this is the case, it should be bundled into a Node module using `#include <node.h>`.

**Comment by TekuConcept** [comment]
Just to clarify, I2C is not asynchronous and can also be blocking is some cases.
If it is insisted upon to convert the current C++ drivers to JavaScript, I highly recommend using the already built-in *bonescript.js* and other pre-existing libraries instead of rolling our own. See the following tutorial by the Beaglebone manufacturer, beagleboard.org: http://beagleboard.org/support/BoneScript/demo_bmp085/
